name: psee_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - networkx
  - matplotlib
  - scipy
  - scikit-learn
  - pip
  - pip:
    - pgmpy
    - causal-learn